<?php
/**
 * Export entry logs.
 *
 *   GET ?format=csv|excel  + the same filters accepted by api/entries.php
 *
 * Excel output is a real .xlsx workbook built by includes/XlsxWriter.php, so
 * Excel opens it without a format-mismatch warning. No Composer package needed.
 */

declare(strict_types=1);

require_once __DIR__ . '/../includes/auth.php';
require_once __DIR__ . '/../includes/XlsxWriter.php';
require_once __DIR__ . '/filters.php';

require_login();

$format    = strtolower((string) ($_GET['format'] ?? 'csv'));
$threshold = temp_threshold();
$pdo       = db();

[$where, $params] = entry_filters($_GET, $threshold);

$stmt = $pdo->prepare(
    "SELECT id, person_name, employee_id, temperature, entry_date, entry_time,
            disinfection_status, misting_status, access_status, remarks, device_id
       FROM entries
       $where
      ORDER BY entry_date DESC, entry_time DESC
      LIMIT 50000"
);
$stmt->execute($params);
$rows = $stmt->fetchAll();

$farm      = setting('farm_name', 'Poultry Farm');
$sysName   = setting('system_name', 'DisinfEntry');
$filterTxt = describe_filters($_GET);
$stamp     = date('Ymd_His');
$me        = current_user();

audit(sprintf('Exported %d entry log(s) as %s', count($rows), strtoupper($format)), 'Entry Monitoring');

$headers = ['Entry ID', 'Temperature (°C)', 'Entry Date',
            'Entry Time', 'Disinfection Status', 'Misting', 'Access Status', 'Remarks', 'Device'];

/* ============================================================
 * CSV
 * ========================================================== */
if ($format === 'csv') {
    header('Content-Type: text/csv; charset=utf-8');
    header("Content-Disposition: attachment; filename=\"entry_logs_$stamp.csv\"");
    header('Pragma: no-cache');

    $out = fopen('php://output', 'w');
    fwrite($out, "\xEF\xBB\xBF"); // BOM so Excel reads UTF-8 correctly

    fputcsv($out, [$sysName . ' — Entry Log Export']);
    fputcsv($out, ['Farm', $farm]);
    fputcsv($out, ['Generated', date('Y-m-d H:i:s')]);
    fputcsv($out, ['Generated by', $me['full_name'] . ' (' . $me['username'] . ')']);
    fputcsv($out, ['Filters', $filterTxt]);
    fputcsv($out, ['Temperature threshold', $threshold . ' C']);
    fputcsv($out, ['Total records', count($rows)]);
    fputcsv($out, []);
    fputcsv($out, $headers);

    foreach ($rows as $r) {
        fputcsv($out, [
            'ENT-' . str_pad((string) $r['id'], 6, '0', STR_PAD_LEFT),
            number_format((float) $r['temperature'], 1),
            date('Y-m-d', strtotime((string) $r['entry_date'])),
            date('h:i:s A', strtotime((string) $r['entry_time'])),
            ucfirst((string) $r['disinfection_status']),
            strtoupper((string) $r['misting_status']),
            ucfirst((string) $r['access_status']),
            csv_safe($r['remarks'] ?: ''),
            csv_safe($r['device_id'] ?: ''),
        ]);
    }

    fclose($out);
    exit;
}

/* ============================================================
 * Excel (.xlsx)
 * ========================================================== */
$x = new XlsxWriter('Entry Logs');
$x->setColumns([13, 15, 13, 13, 17, 10, 14, 44, 17]);

$x->addRow([$sysName . ' — Entry Log Export'], XlsxWriter::S_TITLE);
$x->addRow([$farm], XlsxWriter::S_META);
$x->addRow(['Generated ' . date('F d, Y h:i A') . ' by ' . $me['full_name']
            . ' (' . role_label($me['role']) . ')'], XlsxWriter::S_META);
$x->addRow(['Filters: ' . $filterTxt], XlsxWriter::S_META);
$x->addRow([sprintf('Temperature threshold: %.1f °C  ·  %d record(s)', $threshold, count($rows))],
           XlsxWriter::S_META);
$x->addBlankRow();

$x->addHeader($headers);
$x->freezeHere();

foreach ($rows as $r) {
    $temp   = (float) $r['temperature'];
    $isHigh = $temp > $threshold;
    $denied = $r['access_status'] === 'denied';

    $x->addRow([
        'ENT-' . str_pad((string) $r['id'], 6, '0', STR_PAD_LEFT),
        $temp,
        date('Y-m-d', strtotime((string) $r['entry_date'])),
        date('h:i:s A', strtotime((string) $r['entry_time'])),
        ucfirst((string) $r['disinfection_status']),
        strtoupper((string) $r['misting_status']),
        ucfirst((string) $r['access_status']),
        $r['remarks'] ?: '',
        $r['device_id'] ?: '',
    ], [
        XlsxWriter::S_CENTER,
        $isHigh ? XlsxWriter::S_HIGH : XlsxWriter::S_NUMBER,
        XlsxWriter::S_CENTER,
        XlsxWriter::S_CENTER,
        XlsxWriter::S_CENTER,
        XlsxWriter::S_CENTER,
        $denied ? XlsxWriter::S_DENIED : XlsxWriter::S_GRANTED,
        XlsxWriter::S_TEXT,
        XlsxWriter::S_CENTER,
    ]);
}

if (!$rows) {
    $x->addRow(['No records matched the selected filters.'], XlsxWriter::S_TEXT);
}

$x->download("entry_logs_$stamp.xlsx");
