<?php
/**
 * Report export.
 *
 *   GET ?format=excel&preset=...   → real .xlsx workbook
 *   GET ?format=csv&preset=...     → .csv download
 *   GET ?format=pdf&preset=...     → print-ready sheet that opens the browser's
 *                                    print dialog (choose "Save as PDF")
 *
 * The PDF route uses the browser print engine so the project stays dependency
 * free on XAMPP; no Composer package is required.
 */

declare(strict_types=1);

require_once __DIR__ . '/../includes/auth.php';
require_once __DIR__ . '/../includes/XlsxWriter.php';
require_login();

$pdo       = db();
$threshold = temp_threshold();

$format = strtolower((string) ($_GET['format'] ?? 'pdf'));
$preset = (string) ($_GET['preset'] ?? 'daily');
if (!in_array($preset, ['daily', 'weekly', 'monthly', 'yearly', 'custom'], true)) {
    $preset = 'daily';
}

[$start, $end] = report_range($preset, $_GET['from'] ?? null, $_GET['to'] ?? null);
if (strtotime($start) > strtotime($end)) {
    [$start, $end] = [$end, $start];
}

/* ---- Summary ---- */
$stmt = $pdo->prepare(
    'SELECT COUNT(*) AS total,
            SUM(access_status = "granted") AS passed,
            SUM(access_status = "denied")  AS denied,
            SUM(temperature > ?)           AS high_temp,
            AVG(temperature)               AS avg_temp,
            MIN(temperature)               AS min_temp,
            MAX(temperature)               AS max_temp
       FROM entries WHERE entry_date BETWEEN ? AND ?'
);
$stmt->execute([$threshold, $start, $end]);
$s = $stmt->fetch() ?: [];
$total = (int) ($s['total'] ?? 0);

/* ---- Rows ---- */
$stmt = $pdo->prepare(
    'SELECT id, temperature, entry_date, entry_time, disinfection_status,
            misting_status, access_status, remarks, device_id
       FROM entries
      WHERE entry_date BETWEEN ? AND ?
      ORDER BY entry_date DESC, entry_time DESC
      LIMIT 20000'
);
$stmt->execute([$start, $end]);
$rows = $stmt->fetchAll();

$farm    = setting('farm_name', 'Poultry Farm');
$sysName = setting('system_name', 'DisinfEntry');
$title   = range_label($preset, $start, $end);
$me      = current_user();
$stamp   = date('Ymd_His');
$avgTemp = $s['avg_temp'] !== null ? number_format((float) $s['avg_temp'], 2) : '—';

audit(sprintf('Exported %s report as %s', $preset, strtoupper($format)), 'Reports');

$summaryPairs = [
    'Total Entries'         => number_format($total),
    'Passed'                => number_format((int) ($s['passed'] ?? 0)),
    'Denied'                => number_format((int) ($s['denied'] ?? 0)),
    'High Temperature'      => number_format((int) ($s['high_temp'] ?? 0)),
    'Average Temperature'   => $avgTemp . ' °C',
    'Lowest / Highest'      => ($s['min_temp'] !== null ? number_format((float) $s['min_temp'], 1) : '—')
                             . ' / ' . ($s['max_temp'] !== null ? number_format((float) $s['max_temp'], 1) : '—') . ' °C',
    'Pass Rate'             => ($total > 0 ? round((int) $s['passed'] / $total * 100, 1) : 0) . '%',
];

/* Same layout as the Entry Monitoring export (api/export.php). */
$headers = ['Entry ID', 'Temperature (°C)', 'Entry Date',
            'Entry Time', 'Disinfection Status', 'Misting', 'Access Status', 'Remarks', 'Device'];

$periodTxt = $title . '  (' . fmt_date($start) . ' to ' . fmt_date($end) . ')';

/* ============================================================
 * CSV
 * ========================================================== */
if ($format === 'csv') {
    header('Content-Type: text/csv; charset=utf-8');
    header("Content-Disposition: attachment; filename=\"{$preset}_report_$stamp.csv\"");
    header('Pragma: no-cache');

    $out = fopen('php://output', 'w');
    fwrite($out, "\xEF\xBB\xBF"); // BOM so Excel reads UTF-8 correctly

    fputcsv($out, [$sysName . ' — Entry Log Export']);
    fputcsv($out, ['Farm', $farm]);
    fputcsv($out, ['Generated', date('Y-m-d H:i:s')]);
    fputcsv($out, ['Generated by', $me['full_name'] . ' (' . $me['username'] . ')']);
    fputcsv($out, ['Filters', $periodTxt]);
    fputcsv($out, ['Temperature threshold', $threshold . ' C']);
    fputcsv($out, ['Total records', count($rows)]);
    fputcsv($out, []);
    fputcsv($out, $headers);

    foreach ($rows as $r) {
        fputcsv($out, [
            'ENT-' . str_pad((string) $r['id'], 6, '0', STR_PAD_LEFT),
            number_format((float) $r['temperature'], 1),
            date('Y-m-d', strtotime((string) $r['entry_date'])),
            date('h:i:s A', strtotime((string) $r['entry_time'])),
            ucfirst((string) $r['disinfection_status']),
            strtoupper((string) $r['misting_status']),
            ucfirst((string) $r['access_status']),
            csv_safe($r['remarks'] ?: ''),
            csv_safe($r['device_id'] ?: ''),
        ]);
    }

    fclose($out);
    exit;
}

/* ============================================================
 * Excel (.xlsx)
 * ========================================================== */
if ($format === 'excel') {
    $x = new XlsxWriter(ucfirst($preset) . ' Report');
    $x->setColumns([13, 15, 13, 13, 17, 10, 14, 44, 17]);

    $x->addRow([$sysName . ' — Entry Log Export'], XlsxWriter::S_TITLE);
    $x->addRow([$farm], XlsxWriter::S_META);
    $x->addRow(['Generated ' . date('F d, Y h:i A') . ' by ' . $me['full_name']
                . ' (' . role_label($me['role']) . ')'], XlsxWriter::S_META);
    $x->addRow(['Filters: ' . $periodTxt], XlsxWriter::S_META);
    $x->addRow([sprintf('Temperature threshold: %.1f °C  ·  %d record(s)', $threshold, count($rows))],
               XlsxWriter::S_META);
    $x->addBlankRow();

    $x->addHeader($headers);
    $x->freezeHere();

    foreach ($rows as $r) {
        $temp   = (float) $r['temperature'];
        $isHigh = $temp > $threshold;
        $denied = $r['access_status'] === 'denied';

        $x->addRow([
            'ENT-' . str_pad((string) $r['id'], 6, '0', STR_PAD_LEFT),
            $temp,
            date('Y-m-d', strtotime((string) $r['entry_date'])),
            date('h:i:s A', strtotime((string) $r['entry_time'])),
            ucfirst((string) $r['disinfection_status']),
            strtoupper((string) $r['misting_status']),
            ucfirst((string) $r['access_status']),
            $r['remarks'] ?: '',
            $r['device_id'] ?: '',
        ], [
            XlsxWriter::S_CENTER,
            $isHigh ? XlsxWriter::S_HIGH : XlsxWriter::S_NUMBER,
            XlsxWriter::S_CENTER,
            XlsxWriter::S_CENTER,
            XlsxWriter::S_CENTER,
            XlsxWriter::S_CENTER,
            $denied ? XlsxWriter::S_DENIED : XlsxWriter::S_GRANTED,
            XlsxWriter::S_TEXT,
            XlsxWriter::S_CENTER,
        ]);
    }

    if (!$rows) {
        $x->addRow(['No records matched the selected period.'], XlsxWriter::S_TEXT);
    }

    $x->download("{$preset}_report_$stamp.xlsx");
}

/* ============================================================
 * PDF (browser print sheet)
 * ========================================================== */
?>
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title><?= e($title) ?> · <?= e($sysName) ?></title>
<style>
  @page { size: A4 landscape; margin: 12mm; }
  body { font-family: "Segoe UI", Arial, sans-serif; color: #1e293b; margin: 0; padding: 18px 24px; }
  .sheet { max-width: 1100px; margin: 0 auto; }
  .head { border-bottom: 3px solid #0d7a5f; padding-bottom: 12px; margin-bottom: 18px; }
  .head h1 { margin: 0 0 2px; font-size: 20pt; color: #0d7a5f; }
  .head h2 { margin: 0 0 6px; font-size: 13pt; font-weight: 600; }
  .head .meta { font-size: 9pt; color: #64748b; }
  .cards { width: 100%; border-collapse: separate; border-spacing: 8px 0; margin-bottom: 18px; }
  .cards td { border: 1px solid #e5e9f0; border-radius: 8px; padding: 10px 12px; text-align: center;
              background: #fbfcfe; width: 12.5%; }
  .cards .v { font-size: 15pt; font-weight: 700; color: #0f172a; }
  .cards .l { font-size: 7.5pt; color: #64748b; text-transform: uppercase; letter-spacing: .04em; }
  table.data { width: 100%; border-collapse: collapse; }
  table.data th { background: #0d7a5f; color: #fff; padding: 6px 8px; font-size: 9pt;
                  text-align: left; border: 1px solid #0a5f4a; }
  table.data td { border: 1px solid #dde3ea; padding: 5px 8px; font-size: 9pt; }
  table.data tbody tr:nth-child(even) td { background: #f8fafc; }
  .c { text-align: center; }
  .high   { background: #fee2e2 !important; color: #991b1b; font-weight: 700; }
  .denied { background: #fdecee !important; color: #991b1b; font-weight: 700; }
  .granted{ color: #166534; font-weight: 600; }
  .foot { margin-top: 20px; padding-top: 10px; border-top: 1px solid #e5e9f0;
          font-size: 8pt; color: #64748b; display: flex; justify-content: space-between; }
  .signs { margin-top: 34px; display: flex; gap: 60px; font-size: 9pt; }
  .sign { flex: 1; }
  .sign .line { border-top: 1px solid #334155; margin-top: 34px; padding-top: 4px; }
  .toolbar { text-align: right; margin-bottom: 12px; }
  .toolbar button { background: #0d7a5f; color: #fff; border: 0; border-radius: 7px;
                    padding: 8px 16px; font-size: 10pt; cursor: pointer; }
  @media print { .toolbar { display: none; } body { padding: 0; } tr { page-break-inside: avoid; } }
</style>
</head>
<body>
<div class="sheet">

  <div class="toolbar">
    <button onclick="window.print()">Print / Save as PDF</button>
  </div>

  <div class="head">
    <h1><?= e($sysName) ?></h1>
    <h2><?= e($title) ?></h2>
    <div class="meta">
      <?= e($farm) ?> &nbsp;·&nbsp;
      Period: <?= fmt_date($start) ?> to <?= fmt_date($end) ?> &nbsp;·&nbsp;
      Temperature threshold: <?= e((string) $threshold) ?> °C
    </div>
    <div class="meta">
      Generated <?= date('F d, Y h:i A') ?> by <?= e($me['full_name']) ?> (<?= e(role_label($me['role'])) ?>)
    </div>
  </div>

  <table class="cards">
    <tr>
      <?php foreach ($summaryPairs as $label => $value): ?>
        <td><div class="v"><?= e((string) $value) ?></div><div class="l"><?= e($label) ?></div></td>
      <?php endforeach; ?>
    </tr>
  </table>

  <table class="data">
    <thead>
      <tr><?php foreach ($headers as $h): ?><th><?= e($h) ?></th><?php endforeach; ?></tr>
    </thead>
    <tbody>
    <?php foreach ($rows as $r):
        $high = (float) $r['temperature'] > $threshold;
        $den  = $r['access_status'] === 'denied';
    ?>
      <tr>
        <td>ENT-<?= str_pad((string) $r['id'], 6, '0', STR_PAD_LEFT) ?></td>
        <td class="c <?= $high ? 'high' : '' ?>"><?= number_format((float) $r['temperature'], 1) ?></td>
        <td><?= fmt_date($r['entry_date']) ?></td>
        <td><?= fmt_time($r['entry_time']) ?></td>
        <td class="c"><?= e(ucfirst((string) $r['disinfection_status'])) ?></td>
        <td class="c"><?= e(strtoupper((string) $r['misting_status'])) ?></td>
        <td class="c <?= $den ? 'denied' : 'granted' ?>"><?= e(ucfirst((string) $r['access_status'])) ?></td>
        <td><?= e($r['remarks']) ?></td>
        <td><?= e($r['device_id'] ?: '') ?></td>
      </tr>
    <?php endforeach; ?>
    <?php if (!$rows): ?>
      <tr><td colspan="9" class="c">No entries were recorded in this period.</td></tr>
    <?php endif; ?>
    </tbody>
  </table>

  <div class="signs">
    <div class="sign"><div class="line">Prepared by — <?= e($me['full_name']) ?></div></div>
    <div class="sign"><div class="line">Reviewed by</div></div>
    <div class="sign"><div class="line">Noted by — Farm Owner / Manager</div></div>
  </div>

  <div class="foot">
    <span><?= e($sysName) ?> v<?= e(APP_VERSION) ?> — Smart Disinfection &amp; Entry Monitoring System</span>
    <span><?= count($rows) ?> record(s)</span>
  </div>
</div>

<script>window.addEventListener('load', () => setTimeout(() => window.print(), 400));</script>
</body>
</html>
